//
// InlineResponse200Timezone.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Timezone: Codable {

    public var abbreviation: String?
    public var currentTime: String?
    public var gmtOffset: Int?
    public var isDst: Bool?
    public var name: String?

    public init(abbreviation: String? = nil, currentTime: String? = nil, gmtOffset: Int? = nil, isDst: Bool? = nil, name: String? = nil) {
        self.abbreviation = abbreviation
        self.currentTime = currentTime
        self.gmtOffset = gmtOffset
        self.isDst = isDst
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case abbreviation
        case currentTime = "current_time"
        case gmtOffset = "gmt_offset"
        case isDst = "is_dst"
        case name
    }

}
