//
// InlineResponse200Connection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Connection: Codable {

    public var autonomousSystemNumber: Int?
    public var autonomousSystemOrganization: String?
    public var connectionType: String?
    public var ispName: String?
    public var organizationName: String?

    public init(autonomousSystemNumber: Int? = nil, autonomousSystemOrganization: String? = nil, connectionType: String? = nil, ispName: String? = nil, organizationName: String? = nil) {
        self.autonomousSystemNumber = autonomousSystemNumber
        self.autonomousSystemOrganization = autonomousSystemOrganization
        self.connectionType = connectionType
        self.ispName = ispName
        self.organizationName = organizationName
    }

    public enum CodingKeys: String, CodingKey { 
        case autonomousSystemNumber = "autonomous_system_number"
        case autonomousSystemOrganization = "autonomous_system_organization"
        case connectionType = "connection_type"
        case ispName = "isp_name"
        case organizationName = "organization_name"
    }

}
