//
// InlineResponse200Currency.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Currency: Codable {

    public var currencyCode: String?
    public var currencyName: String?

    public init(currencyCode: String? = nil, currencyName: String? = nil) {
        self.currencyCode = currencyCode
        self.currencyName = currencyName
    }

    public enum CodingKeys: String, CodingKey { 
        case currencyCode = "currency_code"
        case currencyName = "currency_name"
    }

}
