//
// InlineResponse200Flag.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Flag: Codable {

    public var emoji: String?
    public var png: String?
    public var svg: String?
    public var unicode: String?

    public init(emoji: String? = nil, png: String? = nil, svg: String? = nil, unicode: String? = nil) {
        self.emoji = emoji
        self.png = png
        self.svg = svg
        self.unicode = unicode
    }


}
