//
// InlineResponse200Security.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Security: Codable {

    public var isVpn: Bool?

    public init(isVpn: Bool? = nil) {
        self.isVpn = isVpn
    }

    public enum CodingKeys: String, CodingKey { 
        case isVpn = "is_vpn"
    }

}
