//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI {
    /**

     - parameter apiKey: (query)  
     - parameter ipAddress: (query)  (optional)
     - parameter fields: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func v1Get(apiKey: String, ipAddress: String? = nil, fields: String? = nil, completion: @escaping ((_ data: InlineResponse200?,_ error: Error?) -> Void)) {
        v1GetWithRequestBuilder(apiKey: apiKey, ipAddress: ipAddress, fields: fields).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/

     - examples: [{contentType=application/json, example={
  "continent" : "continent",
  "country" : "country",
  "flag" : {
    "emoji" : "emoji",
    "svg" : "svg",
    "png" : "png",
    "unicode" : "unicode"
  },
  "country_geoname_id" : 5,
  "city" : "city",
  "city_geoname_id" : 0,
  "country_is_eu" : true,
  "timezone" : {
    "name" : "name",
    "gmt_offset" : 9,
    "abbreviation" : "abbreviation",
    "current_time" : "current_time",
    "is_dst" : true
  },
  "latitude" : 5.637376656633329,
  "continent_code" : "continent_code",
  "ip_address" : "ip_address",
  "region_geoname_id" : 7,
  "region_iso_code" : "region_iso_code",
  "country_code" : "country_code",
  "security" : {
    "is_vpn" : true
  },
  "connection" : {
    "isp_name" : "isp_name",
    "connection_type" : "connection_type",
    "organization_name" : "organization_name",
    "autonomous_system_organization" : "autonomous_system_organization",
    "autonomous_system_number" : 6
  },
  "currency" : {
    "currency_name" : "currency_name",
    "currency_code" : "currency_code"
  },
  "continent_geoname_id" : 1,
  "postal_code" : "postal_code",
  "region" : "region",
  "longitude" : 2.3021358869347655
}}]
     - parameter apiKey: (query)  
     - parameter ipAddress: (query)  (optional)
     - parameter fields: (query)  (optional)

     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func v1GetWithRequestBuilder(apiKey: String, ipAddress: String? = nil, fields: String? = nil) -> RequestBuilder<InlineResponse200> {
        let path = "/v1/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "api_key": apiKey, 
                        "ip_address": ipAddress, 
                        "fields": fields
        ])


        let requestBuilder: RequestBuilder<InlineResponse200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
